import React from 'react';
import {View, StyleSheet} from 'react-native';

import PageLine from './NLPageLine';
import AppColors from '../../config/Colors';

export default class NLNotesPage extends React.Component {
  // _getPageLines = nLines => {
  //   var lines = [];
  //   for (var i = nLines; i > 0; i--) {
  //     lines.push(<PageLine key={i} />);
  //   }
  //   return lines;
  // };

  render = () => {
    return (
      <View style={styles.page}>
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
        <PageLine />
      </View>
    );
  };
}

const styles = StyleSheet.create({
  page: {
    height: 520,
    position: 'absolute',
    top: 0,
    left: 10,
    right: 10,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: AppColors.secondaryAccentColor,
  },
});
